ca devrait marcher 9

diff --git a/.github/workflows/testacc.yml b/.github/workflows/testacc.yml
--- a/.github/workflows/testacc.yml
+++ b/.github/workflows/testacc.yml
@@ -62,8 +62,13 @@ jobs:
           TEST_NAME=$(echo ${{ github.event.comment.body }} | cut -d " " -f2)
           CATEGORY=$(echo $TEST_NAME | sed -r 's/^TestAcc([A-Z][a-z]*).*$/\1/' | tr '[:upper:]' '[:lower:]')
           go test ./internal/tests/$CATEGORY -run $TEST_NAME > 'test_output.txt'
-          if [ $? -ne 0 ]; then
-            echo "Error: Test $TEST_NAME does not exist" > 'test_output.txt'
+          if [ -d "./internal/tests/$CATEGORY" ]; then
+            go test ./internal/tests/$CATEGORY -run $TEST_NAME > 'test_output.txt'
+            if [ $? -ne 0 ]; then
+              echo "Error: Test $TEST_NAME does not exist" > 'test_output.txt'
+            fi
+          else
+            echo "[no tests to run]" > 'test_output.txt'
           fi
         timeout-minutes: 20
       - name: Comment PR with test results
@@ -77,9 +82,9 @@ jobs:
             let comment = "";
             if (output.includes('[no tests to run]')) {
                 comment = "La ressource n'existe pas";
-            } else if (output.startsWith('ok')) {
+            } elseif (output.startsWith('ok')) {
                 comment = "La ressource est correcte";
-            } else if (output.includes('Error: Test')) {
+            } elseif (output.includes('Error: Test')) {
                 comment = "Le test spécifié n'existe pas";
             else {
                 comment = "La ressource n'est pas correcte et renvoie ce message d'erreur : " + output;
